# Stage 1: build the React app
FROM node:16 AS build

RUN apt update && \
	apt install curl -y && \
	apt install sudo && \
	apt install apache2 -y

RUN curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash - && \
	apt update

RUN apt install nodejs -y

# Set the working directory
WORKDIR /app/frontend

CMD apachectl -D FOREGROUND

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the React app
RUN npm run build

# Stage 2: serve the React app using a lightweight web server
FROM nginx:alpine

# Copy the built app from the previous stage to the NGINX web server directory
COPY --from=build /app/frontend /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]


CMD ["npm", "run", "start"]
