version: '3.8'

name: kaoszkviz
services:
#  database:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    environment:
#      - ACCEPT_EULA=Y
#      - SA_PASSWORD=vEU5cmyD4C2HPbG8FjNzTR
#    ports:
#      - "1433:1433"

  backend:
#    depends_on:
#      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - "-no-cache"
    restart: unless-stopped
    ports:
      - "5556:5556"
    volumes:
      - ./backend:/var/backend
#    environment:
#      - SPRING_PROFILES_ACTIVE=development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/frontend

